name: Integration Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    inputs:
      kind: custom
      custom_versions: magento/project-community-edition:2.4.5, magento/project-community-edition:2.4.4
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: graycoreio/github-actions-magento2/supported-version@main
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}
  integration-workflow:
    needs: compute_matrix
    uses: graycoreio/github-actions-magento2/.github/workflows/integration.yaml@main
    with:
      package_name: memegento/module-mage
      matrix: ${{ needs.compute_matrix.outputs.matrix }}
      test_command: ../../../vendor/bin/phpunit ../../../vendor/memegento/module-mage/Test/Integration
    secrets:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
